Building DAG of jobs...
Using shell: /anaconda2/envs/py3/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	3	find_egg_mutations
	4

[Thu Apr 18 11:00:44 2019]
rule find_egg_mutations:
    input: dataframes/h3n2_ha_12y_fra.csv
    output: plots/h3n2_ha_12y_fra/egg_mutation_aa_prevalence_h3n2_ha_12y_fra.pdf, plots/h3n2_ha_12y_fra/egg_mutation_site_prevalence_h3n2_ha_12y_fra.pdf, plots/h3n2_ha_12y_fra/before_after_eggpassaging_h3n2_ha_12y_fra.pdf
    jobid: 12
    wildcards: lineage=h3n2, segment=ha, resolution=12y, assay=fra

[Thu Apr 18 11:00:50 2019]
Finished job 12.
1 of 4 steps (25%) done

[Thu Apr 18 11:00:50 2019]
rule find_egg_mutations:
    input: dataframes/h3n2_ha_6y_fra.csv
    output: plots/h3n2_ha_6y_fra/egg_mutation_aa_prevalence_h3n2_ha_6y_fra.pdf, plots/h3n2_ha_6y_fra/egg_mutation_site_prevalence_h3n2_ha_6y_fra.pdf, plots/h3n2_ha_6y_fra/before_after_eggpassaging_h3n2_ha_6y_fra.pdf
    jobid: 10
    wildcards: lineage=h3n2, segment=ha, resolution=6y, assay=fra

[Thu Apr 18 11:00:56 2019]
Finished job 10.
2 of 4 steps (50%) done

[Thu Apr 18 11:00:56 2019]
rule find_egg_mutations:
    input: dataframes/h3n2_ha_6y_hi.csv
    output: plots/h3n2_ha_6y_hi/egg_mutation_aa_prevalence_h3n2_ha_6y_hi.pdf, plots/h3n2_ha_6y_hi/egg_mutation_site_prevalence_h3n2_ha_6y_hi.pdf, plots/h3n2_ha_6y_hi/before_after_eggpassaging_h3n2_ha_6y_hi.pdf
    jobid: 9
    wildcards: lineage=h3n2, segment=ha, resolution=6y, assay=hi

[Thu Apr 18 11:00:59 2019]
Error in rule find_egg_mutations:
    jobid: 9
    output: plots/h3n2_ha_6y_hi/egg_mutation_aa_prevalence_h3n2_ha_6y_hi.pdf, plots/h3n2_ha_6y_hi/egg_mutation_site_prevalence_h3n2_ha_6y_hi.pdf, plots/h3n2_ha_6y_hi/before_after_eggpassaging_h3n2_ha_6y_hi.pdf

RuleException:
CalledProcessError in line 785 of /Users/katekistler/nextstrain/egg-passage/Snakefile:
Command 'set -euo pipefail;  python3 scripts/find_egg_mutations.py             --in_file dataframes/h3n2_ha_6y_hi.csv' returned non-zero exit status 1.
  File "/Users/katekistler/nextstrain/egg-passage/Snakefile", line 785, in __rule_find_egg_mutations
  File "/anaconda2/envs/py3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job find_egg_mutations since they might be corrupted:
plots/h3n2_ha_6y_hi/egg_mutation_site_prevalence_h3n2_ha_6y_hi.pdf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/katekistler/nextstrain/egg-passage/.snakemake/log/2019-04-18T110042.680226.snakemake.log
